name: Action

on: 
  push:

jobs: 
  setup-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        run: 
          git clone https://github.com/luisgustavobueno/Pull