name: Action

on: 
  push:

jobs: 
  setup-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clonando para o repositorio
        run: |
          git config --global user.name "Luis"
          git config --global user.email "luisgustavobuenocolombo@gmail.com"
          git clone https://github.com/luisgustavobueno/Pull
          git add -A
          git commit -m "Commito da action"
          git push