name: Action

on: 
  push:

jobs: 
  setup-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clone
        run: 
          git clone https://github.com/luisgustavobueno/Pull
      - name: Clonando para o repositorio
        run: |
          git add .
          git commit -m "Commito da action"
          git push